ekmett/semigroupoids

- src/Data/Functor/Alt.hs
- src/Data/Functor/Bind.hs
- src/Data/Functor/Plus.hs
- src/Data/Semigroup/Foldable.hs
- src/Data/Semigroup/Traversable.hs
As part of my mission to add more `FoldableWithKey1` and `TraversableWithKey1` instances to `keys`, I need to have corresponding `Foldable1` and `Traversable1` instances in `semigroupoids`. As it turns out, all of these data types are in `transformers`, so I went ahead and added all of the missing instances for data types in `transformers` (or `transformers-compat`)—namely, `Alt`, `Apply`, `Plus`, `Foldable1`, and `Traversable1` instances for `Backwards`, `Compose`, `ExceptT`, `Lift`, `Product`, `Reverse`, and `Sum`, where appropriate.
> Instances for transformers(-compat) types

- semigroupoids.cabal
- src/Data/Traversable/Instances.hs
My second attempt (after #27) at consolidating some surprisingly common orphan instances that appear in `semigroupoids` (as well as [`functor-combo`](https://github.com/conal/functor-combo/blob/885752a0b58a2e9e606401da9ed8a4f0fe823680/src/FunctorCombo/Functor.hs#L115-118), [`infernu`](https://github.com/sinelaw/infernu/blob/405685e3cc92ddc722d4bb0ea549b21553cce1f2/src/Infernu/Prelude.hs#L40-43), [`witherable`](https://github.com/fumieval/witherable/blob/ea39bbf04ce9ef2e12711601c88605276f2af68d/src/Data/Witherable.hs#L125-139), ...) by means of a common package for these orphans.
To impose less of a burden (as opposed to [`base-compat`](http://hackage.haskell.org/package/base-compat)) on introducing a new dependency for this package, `base-orphans`:
* Defines orphan instances and nothing …
> Use base-orphans to import Foldable/Traversable orphan instances

- semigroupoids.cabal
> add changelog to the tarball

- src/Data/Functor/Extend.hs
- src/Data/Semigroup/Foldable/Class.hs
- src/Data/Semigroup/Traversable/Class.hs
The HEAD version of `comonad` has removed `Coproduct` in favor of `Sum`, so I did the same with `semigroupoids`. I also added an `Extend` instance for `Sum` to compensate for the removed `Extend` instance for `Coproduct`.
I had to fix this in the process of dealing with [this issue](https://github.com/ekmett/free/pull/123).
> Remove Coproduct instances, add Sum instance

- semigroupoids.cabal
- src/Data/Traversable/Instances.hs
Also bumps the upper version bounds of `comonad`, which happened on Hackage but not here.
> Consolidate transformers-related orphans with transformers-compat-0.5

- CHANGELOG.markdown
- src/Data/Functor/Bind/Class.hs
- src/Data/Semigroup/Foldable/Class.hs
- src/Data/Semigroup/Traversable/Class.hs
This adopts some [orphan instances](http://hackage.haskell.org/package/linear-1.20.6/docs/src/Linear-Instances.html) from `linear`.
> Add Apply, Bind, Foldable1, Traversable1 instances for Complex

- src/Data/Semigroup/Foldable.hs
- src/Data/Semigroup/Foldable/Class.hs
Added the function `toNonEmpty` to the `Foldbable1` type-class. 
This allows a `Foldable1` type to produce a non-empty list of it's elements, analogous to a `Foldable` type's ability to produce a (possibly empty) list it's elements.
However `toNonEmpty` preserves the additional constraint that the non-empty structure of `Foldable1` produces a non-empty list.
While a `Foldable` structure can have "list-like" operations performed on it's elements my calling `toList` on the structure and then using functions from `Prelude` or `Data.List`, the addition of `toNonEmpty` allows for "list-like" operations from `Data.List.NonEmpty` to be performed on the elements of a `Foldable1` _in a type-safe manner_ after calling `toNonEmpty` on the structure.
I also implemented `foldrM1` and `foldlM1` …
> Adding toNonEmpty, foldrM1, & foldlM1 to Foldable1 module.

- CHANGELOG.markdown
- semigroupoids.cabal
- src/Data/Functor/Bind/Class.hs
This migrates two more orphan instances from `linear`. Doing this will require incurring an additional `unordered-containers` dependency, but I think this is reasonable.
> Add Apply, Bind instances for HashMap

- src/Data/Functor/Alt.hs
- src/Data/Functor/Bind/Trans.hs
- src/Data/Semigroup/Bitraversable.hs
- src/Data/Semigroup/Traversable.hs
`Data.Semigroup` no longer exports `Monoid(..)` in GHC HEAD, so some minor import surgery is required to fix the `semigroupoids` build.
> Fix the build post-Semigroup–Monoid Proposal

- CHANGELOG.markdown
- semigroupoids.cabal
- src/Data/Functor/Bind/Class.hs
template-haskell is already a transitive dependency (via bifunctors).
I left template-haskell boundsless in build-depends because it's tied to the GHC being used, and defining these instances doesn't actually use any of the things that are ever going to change.
> Apply and Bind instances for Q (from template-haskell).

- CHANGELOG.markdown
- src/Data/Functor/Alt.hs
- src/Data/Functor/Plus.hs
No instances for `Min` and `Max` because of the `Ord` constraint.
> Alt and Plus instances for Data.(Semigroup|Monoid).(First|Last)

- CHANGELOG.markdown
- semigroupoids.cabal
- src/Data/Functor/Bind/Class.hs
- src/Data/Semigroup/Foldable/Class.hs
- src/Data/Semigroup/Traversable/Class.hs
The two commits first bump it to 0.16.2 for CPP reduction, then conditionalise it on having an old GHC.
> Conditionalise the semigroups dep

- src/Data/Functor/Extend.hs
Forward-compatibility for [GHC Proposal 229](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0229-whitespace-bang-patterns.rst)
> No whitespace after the '@' in as-patterns

- src/Data/Functor/Apply.hs
- src/Data/Functor/Bind/Class.hs
- src/Data/Semigroup/Traversable.hs
I was struggling to define such instances (in fact, I was trying to
write a `Traversal1` from `lens`, but it's the same problem), until I
found this [helpful
issue](https://github.com/ekmett/semigroupoids/issues/66) that shows how
to combine `Traversable` and `Traversable1` sub-structures using
`MaybeApply`.
I think this is very helpful for users, so I've added the functions from
the issue, another missing function, which I've called
`traverse1Maybe`, and a simple example so users can see how to put them
together.
Fixes #66.
> Add helpers for defining Traversable1 instances

- CHANGELOG.markdown
- src/Data/Functor/Alt.hs
`Identity` can be a valid instance of `Alt` in two ways. I decided to go with 'choose the first option every time', as it satisfies both extra laws, while 'choose the last option every time' only satisfies one.
> Add Alt instance for Identity

- CHANGELOG.markdown
- semigroupoids.cabal
- src/Data/Functor/Alt.hs
- src/Data/Functor/Contravariant/Conclude.hs
- src/Data/Functor/Contravariant/Decide.hs
- src/Data/Functor/Contravariant/Divise.hs
Supercedes #96. Additionally, repairs all issues raised by @RyanGlScott (I hope!), as well as providing three separate diagrams showing relationships among the newly-added (and existing) type classes. I've also taken the liberty of amending the changelog, adding `@since`s everywhere, and putting `Safe` pragmata in each of the new modules.
> Contravariant analogues of Apply/Alt/Plus (with revisions)

- CHANGELOG.markdown
- semigroupoids.cabal
- src/Data/Functor/Alt.hs
- src/Data/Functor/Bind/Class.hs
- src/Data/Functor/Contravariant/Conclude.hs
- src/Data/Functor/Contravariant/Decide.hs
- src/Data/Functor/Contravariant/Divise.hs
- src/Data/Functor/Plus.hs
- src/Data/Semigroup/Foldable/Class.hs
This is an alternative to the current approach in `master`. Rather than remove the instances for `Option` entirely (see f8dd1b980790d0705bdae52ea39b57f62b5ad8cd), we now guard them behind CPP. This avoids the need for a major version bump. We adopt a similar approach for the instances for `ErrorT` and `ListT`, which cannot co-exist with `transformers-0.6.*`.
Resolves #109.
> Allow building with GHC 9.2, `transformers-0.6.*`

- src/Data/Functor/Alt.hs
- src/Data/Functor/Plus.hs
The methods of `Bind` are not used in these instances. `Functor` is still needed for older GHC versions where it is not yet a transitive superclass of `Monad`.
> Replace Bind constraints with Functor for Alt instances where possible

- semigroupoids.cabal
- src/Data/Semigroup/Traversable/Class.hs
Then we can define Traversable1 instances for Reverse, Backwards etc. unconditionally
If `semigroupoids-6` is blakclisted and `semigroupoids-6.0.0.1` released with this patch, it should indirectly fix https://github.com/ekmett/lens/issues/1028
> Require transformers >= 0.6.1.0 with GHC-9.6

- .github/workflows/haskell-ci.yml
- cabal.haskell-ci
- semigroupoids.cabal
- src/Data/Functor/Contravariant/Conclude.hs
- src/Data/Functor/Contravariant/Decide.hs
- src/Data/Functor/Contravariant/Divise.hs
For the most part, this is a matter of guarding the relevant definitions behind `defined(MIN_VERSION_contravariant)` CPP. I also altered some definitions to avoid relying on the `contravariant` library where they didn't need to do so.
Fixes #136.
> Fix the build with `-contravariant`
